$CMPSSuppressFastNotUsedCheck = $true


. ..\config.ps1


$SearchString = "Automated by Yoink4CM"

#Define the date used to filter packages (only packages created BEFORE this date will be included).
$CutoffDate = (Get-Date).AddDays(-120)



try {
    $RestoreLocation = get-location
    Set-Location "C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin"
    Import-Module .\ConfigurationManager.psd1


    if (-not $Sitecode) {
        throw "The \$Sitecode variable is not defined. Ensure it is set in '..\config.ps1'."
    }
    set-location $Sitecode -ErrorAction Stop
    
    Write-Host "Successfully connected to site $($Sitecode)." -ForegroundColor Green
}
catch {
    Write-Error "Failed to connect to site $($Sitecode). Check if the site code is correct and you have appropriate permissions. Error: $($_.Exception.Message)"
    exit 1
}

Write-Host "`nSearching for packages with comments containing: '$SearchString' created before $($CutoffDate.ToString('yyyy-MM-dd'))..." -ForegroundColor Yellow



$MatchingPackages = Get-CMPackage | Where-Object {

    $CommentMatch = $_.Description -ne $null -and $_.Description -like "*$SearchString*"
    $DateMatch = $_.SourceDate -lt $CutoffDate
    
    $CommentMatch -and $DateMatch
}


if ($MatchingPackages) {
    $Count = $MatchingPackages.Count
    Write-Host "`n--- Found $Count Matching Package(s) ---" -ForegroundColor Green 

    # Display the list of packages found 
    Write-Host "`nList of stale packages generated by Yoink4CM:" -ForegroundColor White
    $MatchingPackages | Select-Object -Property @(
        @{Name='Package Name'; Expression={$_.Name}},
        @{Name='Package ID'; Expression={$_.PackageID}}
        #@{Name='Creation Date'; Expression={$_.SourceDate}}
        
    ) | Format-Table -AutoSize
    Write-Host "------------------------------------------------" -ForegroundColor Green

    # Array to track actions taken
    $ActionSummary = @()
    
    Write-Host "`n--- Starting Interactive Deletion Process ---" -ForegroundColor Yellow

    foreach ($Package in $MatchingPackages) {
        $PackageName = $Package.Name
        $PackageID = $Package.PackageID
        Write-Host "`nPackage: $PackageName ($PackageID)" -ForegroundColor Yellow

        # Loop until valid input (y or n) is received
        do {
            $Prompt = Read-Host "Do you want to DELETE this package and all associated deployments/programs? (y/n)"
            $Confirmation = $Prompt.Trim().ToLower()
        } while ($Confirmation -ne 'y' -and $Confirmation -ne 'n')

        if ($Confirmation -eq 'y') {
            Write-Host "Attempting to delete all components for '$PackageName'..." -ForegroundColor Red
            

            $SuccessfulDeletion = $true

            try {

                Write-Host "  - Deleting associated deployments..." -ForegroundColor Cyan

                $Deployments = Get-CMProgram -PackageId $PackageID
                foreach ($Deployment in $Deployments) {
                    Write-Host "    - Deleting deployment for Program '$($Deployment.ProgramName)' on Collection '$($Deployment.CollectionName)'"
                    Remove-CMPackageDeployment -InputObject $Deployment -Force -ErrorAction SilentlyContinue 
                }
                

                Write-Host "  - Deleting associated programs..." -ForegroundColor Cyan
   
                $Programs = Get-CMProgram -PackageId $PackageID
                foreach ($Program in $Programs) {
                    Write-Host "    - Deleting Program '$($Program.ProgramName)'"
                    Remove-CMProgram -InputObject $Program -Force  -ErrorAction SilentlyContinue 
                }


                Write-Host "  - Deleting the package itself..." -ForegroundColor Cyan
                # Use -Force to suppress the confirmation prompt from Remove-CMPackage
                Remove-CMPackage -InputObject $Package -Force -ErrorAction SilentlyContinue 

                # Record successful deletion
                $ActionSummary += [PSCustomObject]@{
                    'PackageName' = $PackageName;
                    'Action' = "DELETED (Deployments, Programs, Package)";
                    'Status' = "Success"
                }
                Write-Host "Successfully DELETED all components for '$PackageName'." -ForegroundColor Green
            }
            catch {
                # Record the failure
                $ActionSummary += [PSCustomObject]@{
                    'PackageName' = $PackageName;
                    'Action' = "DELETION FAILED";
                    'Status' = $_.Exception.Message
                }
                Write-Error "Failed to fully delete '$PackageName'. Error: $($_.Exception.Message)"
            }
        } else {
            # Record skipping the deletion
            $ActionSummary += [PSCustomObject]@{
                'PackageName' = $PackageName;
                'Action' = "SKIPPED";
                'Status' = "User chose 'n'"
            }
            Write-Host "Skipped deletion of '$PackageName'." -ForegroundColor Cyan
        }
    }
    
    Write-Host "`n--- Final Deletion Summary ---" -ForegroundColor Yellow
    # Display the summary of actions
    $ActionSummary | Format-Table -AutoSize

} else {
    Write-Host "`nNo packages found with the administrative comment containing '$SearchString' and created before $($CutoffDate.ToString('yyyy-MM-dd'))." -ForegroundColor Yellow
}


write-host "Press Enter to continue..."
read-host