. ..\config.ps1


$SearchString = "Automated by Yoink4CM"

#Define the date used to filter applications (today - 120 days).
$CutoffDate = (Get-Date).AddDays(-120)




try {
	$RestoreLocation = get-location
	Set-Location "C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin"
	Import-Module .\ConfigurationManager.psd1

	set-location $Sitecode -ErrorAction Stop
	
    Write-Host "Successfully connected to site $($Sitecode)." -ForegroundColor Green
}
catch {
    Write-Error "Failed to connect to site $($Sitecode). Check if the site code is correct and you have appropriate permissions."
    exit 1
}

Write-Host "`nSearching for applications with comments containing: '$SearchString' created before $($CutoffDate.ToString('yyyy-MM-dd'))..." -ForegroundColor Yellow


$MatchingApps = Get-CMApplication | Where-Object {
    $CommentMatch = $_.LocalizedDescription -ne $null -and $_.LocalizedDescription -like "*$SearchString*"
    $DateMatch = $_.DateCreated -lt $CutoffDate
    
    $CommentMatch -and $DateMatch
}


if ($MatchingApps) {
    $Count = $MatchingApps.Count
    Write-Host "`n--- Found $Count Matching Application(s) ---" -ForegroundColor Green

    # Display the list of applications found 
    Write-Host "`nList of stale applications generated by Yoink4CM:" -ForegroundColor White
    $MatchingApps | Select-Object -Property @(
        @{Name='App Name'; Expression={$_.LocalizedDisplayName}},
        @{Name='ID'; Expression={$_.CI_UniqueID}},
        @{Name='Created Date'; Expression={$_.DateCreated | Get-Date -Format 'yyyy-MM-dd HH:mm'}},
        @{Name='Admin Comment Snippet'; Expression={
            # Truncate the comment for display purposes
            $_.LocalizedDescription.Substring(0, [System.Math]::Min(100, $_.LocalizedDescription.Length)) + '...'
        }}
    ) | Format-Table -AutoSize
    Write-Host "------------------------------------------------" -ForegroundColor Green

    # Array to track actions taken
    $ActionSummary = @()
    
    Write-Host "`n--- Starting Interactive Deletion Process ---" -ForegroundColor Yellow

    foreach ($App in $MatchingApps) {
        $AppName = $App.LocalizedDisplayName
        $AppID = $App.CI_UniqueID
        Write-Host "`nApplication: $AppName ($AppID)" -ForegroundColor Yellow

        # Loop until valid input (y or n) is received
        do {
            $Prompt = Read-Host "Do you want to DELETE this application? (y/n)"
            $Confirmation = $Prompt.Trim().ToLower()
        } while ($Confirmation -ne 'y' -and $Confirmation -ne 'n')

        if ($Confirmation -eq 'y') {
            Write-Host "Attempting to delete '$AppName'..." -ForegroundColor Red
            try {
                # Use -Force to suppress the confirmation prompt from Remove-CMApplication
                Remove-CMApplication -InputObject $App -Force -ErrorAction Stop
                $ActionSummary += [PSCustomObject]@{
                    'ApplicationName' = $AppName;
                    'Action' = "DELETED";
                    'Status' = "Success"
                }
                Write-Host "Successfully DELETED '$AppName'." -ForegroundColor Green
            }
            catch {
                $ActionSummary += [PSCustomObject]@{
                    'ApplicationName' = $AppName;
                    'Action' = "DELETION FAILED";
                    'Status' = $_.Exception.Message
                }
                Write-Error "Failed to delete '$AppName'. Error: $($_.Exception.Message)"
            }
        } else {
            $ActionSummary += [PSCustomObject]@{
                'ApplicationName' = $AppName;
                'Action' = "SKIPPED";
                'Status' = "User chose 'n'"
            }
            Write-Host "Skipped deletion of '$AppName'." -ForegroundColor Cyan
        }
    }
    
    Write-Host "`n--- Final Deletion Summary ---" -ForegroundColor Yellow
    # Display the summary of actions
    $ActionSummary | Format-Table -AutoSize

} else {
    Write-Host "`nNo applications found with the administrative comment containing '$SearchString' and created before $($CutoffDate.ToString('yyyy-MM-dd'))." -ForegroundColor Yellow
}
write-host "Press Enter to continue..."
read-host